// <auto-generated />
using System;
using HairSalonVN.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HairSalonVN.Database.Migrations
{
    [DbContext(typeof(SalonDbContext))]
    partial class SalonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HairSalonVN.Database.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuestBooking")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("StaffId", "AppointmentDate");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AppointmentDate = new DateTime(2024, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT001",
                            CreatedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000020"),
                            IsGuestBooking = false,
                            Notes = "Cắt tóc ngắn, tạo kiểu bob",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AppointmentDate = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT002",
                            CreatedAt = new DateTime(2024, 3, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000021"),
                            IsGuestBooking = false,
                            Notes = "Cắt kiểu undercut nam",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            AppointmentDate = new DateTime(2024, 3, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT003",
                            CreatedAt = new DateTime(2024, 3, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            IsGuestBooking = false,
                            Notes = "Nhuộm highlight nâu mật ong",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            AppointmentDate = new DateTime(2024, 3, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT004",
                            CreatedAt = new DateTime(2024, 3, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000023"),
                            IsGuestBooking = false,
                            Notes = "Uốn xoăn sóng biển",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000012"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            AppointmentDate = new DateTime(2024, 3, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT005",
                            CreatedAt = new DateTime(2024, 3, 18, 15, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000024"),
                            IsGuestBooking = false,
                            Notes = "Cắt tóc mái bay",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            AppointmentDate = new DateTime(2024, 3, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT006",
                            CreatedAt = new DateTime(2024, 3, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            IsGuestBooking = false,
                            Notes = "Nhuộm toàn bộ màu nâu caramel",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            AppointmentDate = new DateTime(2024, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT007",
                            CreatedAt = new DateTime(2024, 3, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000026"),
                            IsGuestBooking = false,
                            Notes = "Duỗi tóc thẳng mượt",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000015"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            AppointmentDate = new DateTime(2024, 4, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT008",
                            CreatedAt = new DateTime(2024, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000027"),
                            IsGuestBooking = false,
                            Notes = "Gội massage thư giãn",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000014"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            AppointmentDate = new DateTime(2024, 4, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT009",
                            CreatedAt = new DateTime(2024, 4, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000028"),
                            IsGuestBooking = false,
                            Notes = "Khách hủy lịch",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000012"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            AppointmentDate = new DateTime(2024, 4, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT010",
                            CreatedAt = new DateTime(2024, 4, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000029"),
                            IsGuestBooking = false,
                            Notes = "Salon hủy do nhân viên nghỉ ốm",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            AppointmentDate = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT011",
                            CreatedAt = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000020"),
                            IsGuestBooking = false,
                            Notes = "Uốn xoăn lọn công chúa",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000012"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            AppointmentDate = new DateTime(2026, 5, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT012",
                            CreatedAt = new DateTime(2026, 5, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            IsGuestBooking = false,
                            Notes = "Cắt tóc fade",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            AppointmentDate = new DateTime(2026, 5, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT013",
                            CreatedAt = new DateTime(2026, 5, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000024"),
                            IsGuestBooking = false,
                            Notes = "Nhuộm ombre xanh navy",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            AppointmentDate = new DateTime(2026, 5, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT014",
                            CreatedAt = new DateTime(2026, 5, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000026"),
                            IsGuestBooking = false,
                            Notes = "Cắt tóc tầng",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            AppointmentDate = new DateTime(2026, 5, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT015",
                            CreatedAt = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000028"),
                            IsGuestBooking = false,
                            Notes = "Massage da đầu VIP",
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000014"),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Amount = 150000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Method = "Cash",
                            PaidAt = new DateTime(2024, 3, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Amount = 120000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000002"),
                            Method = "Transfer",
                            PaidAt = new DateTime(2024, 3, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Amount = 350000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000003"),
                            Method = "Cash",
                            PaidAt = new DateTime(2024, 3, 18, 13, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Amount = 450000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000004"),
                            Method = "Card",
                            PaidAt = new DateTime(2024, 3, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Amount = 150000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000005"),
                            Method = "Transfer",
                            PaidAt = new DateTime(2024, 3, 22, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Amount = 350000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000006"),
                            Method = "Cash",
                            PaidAt = new DateTime(2024, 3, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Amount = 500000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000007"),
                            Method = "Card",
                            PaidAt = new DateTime(2024, 4, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Amount = 80000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000008"),
                            Method = "Cash",
                            PaidAt = new DateTime(2024, 4, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Amount = 450000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000011"),
                            Method = "Transfer",
                            PaidAt = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Amount = 350000m,
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000013"),
                            Method = "Card",
                            PaidAt = new DateTime(2026, 5, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Comment = "Dịch vụ tuyệt vời! Chị Hương cắt tóc rất đẹp, tư vấn nhiệt tình. Sẽ quay lại lần sau!",
                            CreatedAt = new DateTime(2024, 3, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000002"),
                            Comment = "Anh Tài cắt tóc đẹp, nhưng hơi đông nên phải chờ 15 phút. Chất lượng OK.",
                            CreatedAt = new DateTime(2024, 3, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000021"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000003"),
                            Comment = "Màu nhuộm y như mong đợi! Tóc mềm mượt, không bị khô. Cảm ơn salon rất nhiều!",
                            CreatedAt = new DateTime(2024, 3, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000022"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000004"),
                            Comment = "Uốn xoăn siêu đẹp! Tóc vào nếp hoàn hảo, bồng bềnh tự nhiên. Đáng giá tiền!",
                            CreatedAt = new DateTime(2024, 3, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000023"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000005"),
                            Comment = "Kiểu tóc rất hợp với khuôn mặt tôi. Nhân viên dễ thương, không gian đẹp.",
                            CreatedAt = new DateTime(2024, 3, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000024"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000006"),
                            Comment = "Nâu caramel siêu xinh! Màu đều, lên màu chuẩn. Lần đầu nhuộm mà hoàn toàn hài lòng!",
                            CreatedAt = new DateTime(2024, 3, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000025"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000007"),
                            Comment = "Tóc duỗi thẳng mượt như nhung! Đúng chuẩn như mơ. Sẽ giới thiệu bạn bè!",
                            CreatedAt = new DateTime(2024, 4, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000026"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            AppointmentId = new Guid("00000000-0000-0000-0001-000000000008"),
                            Comment = "Massage da đầu thư giãn cực kỳ! Sau tuần làm việc mệt mỏi thì đây là liệu pháp hoàn hảo.",
                            CreatedAt = new DateTime(2024, 4, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("00000000-0000-0000-0000-000000000027"),
                            Rating = 4
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cắt kiểu theo yêu cầu với các style hiện đại, gội sấy hoàn chỉnh, massage da đầu. Bao gồm tư vấn kiểu tóc phù hợp với khuôn mặt.",
                            DurationMinutes = 45,
                            ImageUrl = "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Cắt Tóc Nam",
                            Price = 120000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cắt tạo kiểu theo xu hướng, tư vấn phong cách phù hợp với khuôn mặt. Sử dụng sản phẩm chăm sóc tóc cao cấp.",
                            DurationMinutes = 60,
                            ImageUrl = "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Cắt Tóc Nữ",
                            Price = 150000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uốn xoăn tự nhiên, sử dụng sản phẩm cao cấp từ Hàn Quốc, bảo hành 1 tháng. Tạo kiểu xoăn sóng biển hoặc xoăn bông.",
                            DurationMinutes = 180,
                            ImageUrl = "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Uốn Tóc Xoăn",
                            Price = 450000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhuộm toàn bộ hoặc highlight, sử dụng thuốc nhuộm hữu cơ Organic. Màu bền đẹp, ít hư tổn tóc.",
                            DurationMinutes = 120,
                            ImageUrl = "https://images.unsplash.com/photo-1620331311520-246422fd82f9?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Nhuộm Tóc",
                            Price = 350000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gội dưỡng chất, massage da đầu thư giãn với tinh dầu thiên nhiên. Giúp giảm stress và cải thiện tuần hoàn máu.",
                            DurationMinutes = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Gội Đầu Massage",
                            Price = 80000m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Duỗi nano collagen, phục hồi tóc hư tổn, kết quả mềm mượt tự nhiên. Bảo hành 3 tháng.",
                            DurationMinutes = 180,
                            ImageUrl = "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&h=600&fit=crop",
                            IsActive = true,
                            Name = "Duỗi Tóc",
                            Price = 500000m
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AvatarUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
                            Bio = "8 năm kinh nghiệm, chuyên tóc Hàn Quốc và tóc nam tính. Đã làm việc tại nhiều salon cao cấp ở Seoul.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Specialty = "Cắt & Nhuộm",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AvatarUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
                            Bio = "Chuyên gia uốn xoăn, duỗi tóc với kỹ thuật Nhật Bản. Tốt nghiệp trường làm đẹp Tokyo.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Specialty = "Uốn & Duỗi",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AvatarUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
                            Bio = "5 năm kinh nghiệm, chuyên nhuộm highlight và ombre. Được đào tạo bài bản về kỹ thuật nhuộm châu Âu.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Specialty = "Nhuộm & Tạo Mẫu",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.StaffService", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StaffId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("StaffServices");

                    b.HasData(
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ServiceId = new Guid("00000000-0000-0000-0000-000000000014")
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@luxehair.vn",
                            FullName = "Nguyễn Minh Nhật",
                            IsActive = true,
                            PasswordHash = "$2a$11$C3jnmGxfQ8Rg7QGiC0x.fuD9x25cWsQtgtdfJ2FcZnEXLDTw/hVF6",
                            Phone = "0900000001",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tai.nguyen@luxehair.vn",
                            FullName = "Nguyễn Minh Tài",
                            IsActive = true,
                            PasswordHash = "$2a$11$zmwVfwVZssmoFteDSp7HjejFACAp4mZyMTeZcNzKcftW.CwetP/Ku",
                            Phone = "0900000002",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nam.tran@luxehair.vn",
                            FullName = "Stylist — Trần Hoàng Nam",
                            IsActive = true,
                            PasswordHash = "$2a$11$ISs4K54igroR4GALtz7IJuqKTV7fiz4WhXpRLAoqJE24.74RakBvW",
                            Phone = "0900000003",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "huong.le@luxehair.vn",
                            FullName = "Stylist — Lê Thị Hương",
                            IsActive = true,
                            PasswordHash = "$2a$11$nLQ.M5AfGALEkB0qXXvsUO0Nvf4Rjkh1xW06Wnjkb2nmsI1ZVInQe",
                            Phone = "0900000004",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mai.pham@gmail.com",
                            FullName = "Khách hàng — Phạm Thị Mai",
                            IsActive = true,
                            PasswordHash = "$2a$11$9K8Qzdk1gGWoCXKbgm869uIpKH57Q5JJ7gcAcHhvlF8ZGUPO0mnxO",
                            Phone = "0912345678",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hung.le@yahoo.com",
                            FullName = "Lê Văn Hùng",
                            IsActive = true,
                            PasswordHash = "$2a$11$18j0KR9hdXKopvLq3uiDie.qErlQxBzgW52BHdeyATihA44IgBkCu",
                            Phone = "0923456789",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chau.tran@outlook.com",
                            FullName = "Trần Minh Châu",
                            IsActive = true,
                            PasswordHash = "$2a$11$XiNZWUIdUrStaSJUjS1Z5uFe3H0.n4Vkf40QR0S2Q.AdXf42HE7gu",
                            Phone = "0934567890",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phi.nguyen@gmail.com",
                            FullName = "Nguyễn Hoàng Phi",
                            IsActive = true,
                            PasswordHash = "$2a$11$OrVCd1CNl8dZY/P55ndQh.wA2X./H3SjGVTMhMH2OdIzhAMpL.xL2",
                            Phone = "0945678901",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lan.vo@gmail.com",
                            FullName = "Võ Thị Lan",
                            IsActive = true,
                            PasswordHash = "$2a$11$OctWat.BwgILDxgnZbsizuTEGe/1u/PhK.1TU.wR4aOy7hxODJgKG",
                            Phone = "0956789012",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tuan.dang@email.com",
                            FullName = "Đặng Minh Tuấn",
                            IsActive = true,
                            PasswordHash = "$2a$11$7OF0JCPNGfJXZUIZomMdn.0cTlRDhmigNQz9.fsMJdtjo53u92OGS",
                            Phone = "0967890123",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoa.bui@gmail.com",
                            FullName = "Bùi Thị Hòa",
                            IsActive = true,
                            PasswordHash = "$2a$11$2pICBzJquua7bPLvacWLkeH4l/1rAVALuJi7KFs5nF7iZxCZVwwly",
                            Phone = "0978901234",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anh.cao@gmail.com",
                            FullName = "Cao Đức Anh",
                            IsActive = true,
                            PasswordHash = "$2a$11$cJWYMNh3EpHHQpkZcclJYOnv5y7.hl42LoGHLi57zd1CGzai.K9qq",
                            Phone = "0989012345",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ha.trinh@gmail.com",
                            FullName = "Trịnh Thu Hà",
                            IsActive = true,
                            PasswordHash = "$2a$11$z14/slHDPLGYOGKubX1k3.U4UI.wLQkaEXSPSDE7AFEkVMmsi7ahe",
                            Phone = "0990123456",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bao.hoang@gmail.com",
                            FullName = "Hoàng Gia Bảo",
                            IsActive = true,
                            PasswordHash = "$2a$11$cJrsfjHAXUnpqVP7zIbr2emxxiYPYynjUfo51BHpC5vZGktooJgBy",
                            Phone = "0901234567",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.WorkingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingHours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000000"),
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000000"),
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000000"),
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000004"),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StaffId = new Guid("00000000-0000-0000-0000-000000000006"),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Appointment", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.User", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HairSalonVN.Database.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HairSalonVN.Database.Entities.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Payment", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("HairSalonVN.Database.Entities.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.RefreshToken", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Review", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("HairSalonVN.Database.Entities.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalonVN.Database.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Staff", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("HairSalonVN.Database.Entities.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.StaffService", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.Service", "Service")
                        .WithMany("StaffServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HairSalonVN.Database.Entities.Staff", "Staff")
                        .WithMany("StaffServices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.WorkingHour", b =>
                {
                    b.HasOne("HairSalonVN.Database.Entities.Staff", "Staff")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Appointment", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("StaffServices");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("StaffServices");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("HairSalonVN.Database.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
